cam0:
  position:
    x: 0.00000000
    y: -0.00000000
    z: -0.00000000
  rotvec:
    x: -0.00000000
    y: -0.00000000
    z: 0.00000000
  R:
    [ 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 
      0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 
      0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 
      0.00000000, 0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1000000.00000000 ]
cam1:
  position:
    x: 0.09265437
    y: -0.01059591
    z: -0.08503430
  rotvec:
    x: -2.16307117
    y: 0.03556243
    z: -2.25636725
  R:
    [ 3193.24268704, 409.26893855, -2722.55466637, -65.94799403, -2055.95954368, -671.97023532, 
      0.00000000, 3756.22895181, 706.36279415, 1276.44234344, 232.45200304, -1494.92724045, 
      0.00000000, 0.00000000, 2722.66561718, 486.39842095, 983.23446189, -236.77437013, 
      0.00000000, 0.00000000, 0.00000000, 979.97706311, 99.83464949, 178.64145103, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 811.67994290, 119.08484727, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 832.53335999 ]
cam2:
  position:
    x: -0.19085369
    y: -0.00794461
    z: -0.24286913
  rotvec:
    x: -2.38139665
    y: -0.01470278
    z: 2.01711447
  R:
    [ 5223.08803213, -431.45028182, 6254.39339774, 152.26350356, -3723.32453834, -452.68975344, 
      0.00000000, 5708.16226392, 677.02080250, 1521.02170013, -234.39471520, 2168.12342784, 
      0.00000000, 0.00000000, 3906.83338275, 207.74451166, -1493.16236528, 62.60193423, 
      0.00000000, 0.00000000, 0.00000000, 1074.53253021, -17.36687025, -369.93637249, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 774.31458684, -108.29875972, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 767.18272613 ]
cam3:
  position:
    x: -0.09910564
    y: -0.01925217
    z: -0.31800383
  rotvec:
    x: 0.01823092
    y: 3.00430950
    z: 0.03780422
  R:
    [ 1234.32523034, 252.93014207, 930.92581414, -191.33869618, 231.19790375, 377.99008955, 
      0.00000000, 1891.28039223, 92.38494088, -23.66349591, 79.67738405, -121.26959317, 
      0.00000000, 0.00000000, 2376.01857289, -389.93380997, 65.78628745, -53.81669052, 
      0.00000000, 0.00000000, 0.00000000, 564.71629859, 240.56291734, 61.83293662, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 929.11395674, 54.48177491, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1229.38968435 ]
