cam0:
  position:
    x: 0.38926273
    y: 2.17743694
    z: 0.21916391
  rotvec:
    x: -1.02797124
    y: 1.25214113
    z: -1.50385750
  R:
    [ 12202.94956334, -80.45877287, 153.00538041, 38.72549467, -2296.45634235, -195.53091848, 
      0.00000000, 12435.20453890, 670.44441045, 2380.75714611, -39.78877526, -115.37583019, 
      0.00000000, 0.00000000, 4682.08959763, 358.59988772, -191.27910997, -29.76254758, 
      0.00000000, 0.00000000, 0.00000000, 1555.19181032, -118.56153358, 11.99458244, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1654.68406955, -131.15422717, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1618.20964699 ]
cam1:
  position:
    x: 0.36598502
    y: 0.19544593
    z: 0.23451524
  rotvec:
    x: -1.19904313
    y: 0.92386842
    z: -1.11798889
  R:
    [ 12153.77202508, 17.18232684, -570.43948227, -77.19362216, -2382.19491254, -175.41253305, 
      0.00000000, 12392.67466032, 428.12371638, 2393.03457233, 29.36778416, 34.43444251, 
      0.00000000, 0.00000000, 4555.85560042, 146.99110489, 100.74729572, 102.04035369, 
      0.00000000, 0.00000000, 0.00000000, 1550.52253486, 167.76682008, 39.68746166, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1642.68399532, -39.66548594, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1645.77224415 ]
cam2:
  position:
    x: 0.33681319
    y: 0.20623056
    z: 2.28972472
  rotvec:
    x: -1.41438374
    y: 1.21294709
    z: -0.99850198
  R:
    [ 12505.72166296, 175.82603622, 275.85833129, 24.67253336, -2288.23216305, 200.82636503, 
      0.00000000, 12566.60695838, -661.25939359, 2310.95723657, 11.25225971, 237.44691586, 
      0.00000000, 0.00000000, 4730.74121527, -150.12357840, -71.30359184, -86.97920767, 
      0.00000000, 0.00000000, 0.00000000, 1099.24954870, 206.44404873, 57.62416853, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1061.51400716, 298.90600549, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1525.25065267 ]
cam3:
  position:
    x: 0.39909007
    y: 2.16650657
    z: 2.27956759
  rotvec:
    x: -1.18738019
    y: 1.50276151
    z: -1.27631927
  R:
    [ 12371.50859016, -160.10701170, -184.44181568, -58.94988290, -2280.68845162, 233.44642225, 
      0.00000000, 12481.55097522, -873.96486189, 2341.57426968, 43.80359941, -191.12961612, 
      0.00000000, 0.00000000, 4687.92880681, -152.67139045, -0.64426539, 73.32078343, 
      0.00000000, 0.00000000, 0.00000000, 1398.09464383, 237.15005747, -43.81724627, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1522.63720583, 325.50029801, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1557.77819528 ]
cam4:
  position:
    x: 5.63120896
    y: 0.12173689
    z: 0.24105888
  rotvec:
    x: -1.22079171
    y: -0.92782025
    z: 1.11947323
  R:
    [ 13511.14805399, 148.90925082, 211.33598074, -9.41029865, -2512.24398823, -262.46890185, 
      0.00000000, 13626.37268318, 895.86139392, 2512.90076043, -66.09793504, -81.74165259, 
      0.00000000, 0.00000000, 4719.44552022, 213.53816494, -164.92909961, 74.04437348, 
      0.00000000, 0.00000000, 0.00000000, 1462.48214917, -237.00889927, 393.14997860, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1579.45519369, 23.39475677, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1393.10998854 ]
cam5:
  position:
    x: 5.62528929
    y: 2.10094164
    z: 0.22884638
  rotvec:
    x: -0.93542278
    y: -1.26519346
    z: 1.52218731
  R:
    [ 13535.63397725, 176.02092344, -1017.98760062, 16.53016646, -2492.34528927, -179.01156185, 
      0.00000000, 13520.48388612, 561.23985675, 2444.50878237, 50.67823398, -214.05095944, 
      0.00000000, 0.00000000, 4880.99076905, 175.50881149, -47.93170690, 80.96643287, 
      0.00000000, 0.00000000, 0.00000000, 937.69616314, -59.47077842, 418.65473428, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 963.25362635, 55.57788479, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1318.45547024 ]
cam6:
  position:
    x: 5.66170093
    y: 2.04888244
    z: 2.26530541
  rotvec:
    x: -1.25970188
    y: -1.47439163
    z: 1.25700059
  R:
    [ 13513.46261277, 47.94493557, 196.11479448, 25.62616000, -2510.09265804, 54.10369552, 
      0.00000000, 13495.24572365, -167.31805912, 2504.87837532, -46.83029068, 3.74903046, 
      0.00000000, 0.00000000, 4701.73439672, -60.23262090, 99.51429813, 7.53379053, 
      0.00000000, 0.00000000, 0.00000000, 1363.84904855, -243.05902256, 62.98295448, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1562.98831819, 231.63669135, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1450.53142847 ]
cam7:
  position:
    x: 5.62230786
    y: 0.18014718
    z: 2.29766455
  rotvec:
    x: -1.49722259
    y: -1.08428057
    z: 0.91450022
  R:
    [ 13504.23566363, 62.67489900, 1120.78603466, 42.06623372, -2471.88026169, 65.89205904, 
      0.00000000, 13627.61063596, -340.86379987, 2471.55386980, -3.50549152, 88.31965924, 
      0.00000000, 0.00000000, 4893.77841332, -132.32482097, 47.03438383, -0.39938190, 
      0.00000000, 0.00000000, 0.00000000, 863.31397804, -252.43725945, -132.36994580, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 711.39611867, -55.45647841, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1324.34254132 ]
