cam0:
  camera_model: pinhole
  intrinsics: [470.338, 470.294, 620.702, 534.861]
  distortion_model: equidistant
  distortion_coeffs: [-0.0177484, -0.00281825, 0.00696388, -0.0030704]
  resolution: [1280, 1024]
  # 16061369
  rostopic: /stereo/left/image_raw/compressed
  tagtopic: /stereo/left/tags
  rig_body: rig
cam1:
  camera_model: pinhole
  intrinsics: [471.126, 471.106, 629.016, 516.566]
  distortion_model: equidistant
  distortion_coeffs: [-0.0179247, 0.00439381, -0.000291545, -0.00076265]
  resolution: [1280, 1024]
  # 16024499
  rostopic: /stereo/right/image_raw/compressed
  tagtopic: /stereo/right/tags
  rig_body: rig
