cam0:
  position:
    x: -0.00000000
    y: -0.00000000
    z: 0.00000000
  rotvec:
    x: 0.00000000
    y: 0.00000000
    z: 0.00000000
  R:
    [ 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 
      0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 
      0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 0.00000000, 
      0.00000000, 0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 0.00000000, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 1000000.00000000, 0.00000000, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 1000000.00000000 ]
cam1:
  position:
    x: 0.19960309
    y: 0.00112311
    z: 0.00304612
  rotvec:
    x:  0.00726372
    y: -0.02501371
    z:  0.00281226
  R:
    [ 8989.82726158, 52.73859355, -250.14415993, 51.67711938, -5392.85843153, -643.86627142, 
      0.00000000, 8557.46826899, 527.45493923, 4463.04657525, 63.95574891, -396.18119694, 
      0.00000000, 0.00000000, 5901.20297321, 434.83318992, -90.72501022, -119.02917491, 
      0.00000000, 0.00000000, 0.00000000, 1522.10347427, -293.05469859, -494.70197292, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 2259.86636076, -326.15278950, 
      0.00000000, 0.00000000, 0.00000000, 0.00000000, 0.00000000, 3292.48908926 ]
